### ISSUE TITLE
login fails

### ISSUE THREAD

**Issue by brakdag** [overjt/taringajs#6]
```javascript
> var t = require('taringajs')
undefined
> var taringa = new t('usuario','clave')
undefined
> Error: Login failed: Request was not succesful
    at Request._callback (D:\temp\taringa\node_modules\taringajs\index.js:63:15)
    at Request.self.callback (D:\temp\taringa\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\temp\taringa\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
>
```

**Comment by doorgan** [comment]
Borra la issue y volvé a crearla, se pueden ver tus credenciales en el historial.

**Comment by brakdag** [comment]
si me dí cuenta después, por eso ya cambié la contraseña en taringa.
